import { act, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import { LinMemories } from './LinMemories'
import { MEMORY_PAGE_SIZE } from '@/lib/api/memories'
const mocks = vi.hoisted(() => ({ client: {}, membership: vi.fn(), fetch: vi.fn(), post: vi.fn() }))
vi.mock('@/lib/supabase/client', () => ({ createClient: () => mocks.client }))
vi.mock('@/lib/viewer', () => ({ useViewer: () => ({ personId: 'person', isAdmin: false }) }))
vi.mock('@/lib/api/lins', () => ({ fetchLinsOf: mocks.membership }))
vi.mock('@/lib/api/memories', async importOriginal => ({ ...await importOriginal<typeof import('@/lib/api/memories')>(), fetchMemories: mocks.fetch, postMemory: mocks.post }))
const lin = { id: 'lin', name: 'Dragons', color: '#123456', founder_id: 'founder' }
const memory = (id: string, paths = [`lin/person/${id}.jpg`]) => ({ id, lin_id: 'lin', author_id: 'person', caption: id, media_paths: paths, created_at: '2026-09-01T12:00:00.000Z', private_to_lin: false, urls: paths.map(p => `blob:${p}`) })
beforeEach(() => {
  vi.clearAllMocks()
  mocks.membership.mockResolvedValue(['lin'])
  mocks.fetch.mockResolvedValue([])
  mocks.post.mockResolvedValue(undefined)
  URL.createObjectURL = vi.fn(() => 'blob:preview')
  URL.revokeObjectURL = vi.fn()
})
it('offers a first memory and publishes the selected file and caption', async () => {
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  expect(await screen.findByText('No memories yet')).toBeInTheDocument()
  const file = new File(['photo'], 'dinner.jpg', { type: 'image/jpeg' })
  await user.upload(screen.getByLabelText('Photos or videos'), file)
  await user.type(screen.getByLabelText(/Caption/), 'Dinner together')
  await user.click(screen.getByRole('button', { name: 'Share memory' }))
  await waitFor(() => expect(mocks.post).toHaveBeenCalledWith(mocks.client, 'lin', 'person', [file], 'Dinner together', false))
  await waitFor(() => expect(screen.getByLabelText(/Caption/)).toHaveValue(''))
})
it('shows public memories but not upload controls to an outsider', async () => {
  mocks.membership.mockResolvedValue([])
  render(<LinMemories lin={lin} />)
  expect(await screen.findByText('Public memories from Dragons will appear here.')).toBeInTheDocument()
  expect(mocks.fetch).toHaveBeenCalled()
  expect(screen.queryByLabelText('Photos or videos')).not.toBeInTheDocument()
})
it('can publish a memory for only the lin', async () => {
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  const file = new File(['photo'], 'dinner.jpg', { type: 'image/jpeg' })
  await user.upload(await screen.findByLabelText('Photos or videos'), file)
  await user.click(screen.getByRole('checkbox', { name: /Only my Lin/ }))
  await user.click(screen.getByRole('button', { name: 'Share memory' }))
  await waitFor(() => expect(mocks.post).toHaveBeenCalledWith(mocks.client, 'lin', 'person', [file], '', true))
})
it('retains the draft when publishing fails', async () => {
  mocks.post.mockRejectedValue(new Error('Upload interrupted'))
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  await user.upload(await screen.findByLabelText('Photos or videos'), new File(['photo'], 'dinner.jpg', { type: 'image/jpeg' }))
  await user.type(screen.getByLabelText(/Caption/), 'Keep this draft')
  await user.click(screen.getByRole('button', { name: 'Share memory' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Upload interrupted')
  expect(screen.getByLabelText(/Caption/)).toHaveValue('Keep this draft')
})
it('ignores a page of memories that a refresh has superseded', async () => {
  const page = (prefix: string) => Array.from({ length: MEMORY_PAGE_SIZE }, (_, i) => memory(`${prefix}${i}`))
  let releaseOlder: (rows: unknown[]) => void = () => {}
  mocks.fetch.mockImplementation((_sb: unknown, _lin: string, offset = 0) =>
    offset ? new Promise(resolve => { releaseOlder = resolve }) : Promise.resolve(page('first')))
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  await user.click(await screen.findByRole('button', { name: 'Older memories' }))
  // The timeline is replaced while that second page is still in flight.
  mocks.fetch.mockImplementation(() => Promise.resolve([memory('after refresh')]))
  await user.upload(screen.getByLabelText('Photos or videos'), new File(['photo'], 'dinner.jpg', { type: 'image/jpeg' }))
  await user.click(screen.getByRole('button', { name: 'Share memory' }))
  expect(await screen.findByText('after refresh')).toBeInTheDocument()
  await act(async () => { releaseOlder(page('stale')) })
  expect(screen.queryByText('stale0')).not.toBeInTheDocument()
  expect(screen.queryByRole('button', { name: 'Older memories' })).not.toBeInTheDocument()
})
it('lets a member pick several files, drop one, and share the rest', async () => {
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  await screen.findByText('No memories yet')
  const files = ['a', 'b', 'c'].map(n => new File([n], `${n}.jpg`, { type: 'image/jpeg' }))
  await user.upload(screen.getByLabelText('Photos or videos'), files)
  expect(screen.getAllByRole('img', { name: /preview/i })).toHaveLength(3)
  await user.click(screen.getByRole('button', { name: 'Remove b.jpg' }))
  expect(screen.getAllByRole('img', { name: /preview/i })).toHaveLength(2)
  await user.click(screen.getByRole('button', { name: 'Share memory' }))
  await waitFor(() => expect(mocks.post).toHaveBeenCalledWith(mocks.client, 'lin', 'person', [files[0], files[2]], '', false))
})
it('refuses more than five files', async () => {
  const user = userEvent.setup()
  render(<LinMemories lin={lin} />)
  await screen.findByText('No memories yet')
  const files = Array.from({ length: 6 }, (_, i) => new File(['x'], `${i}.jpg`, { type: 'image/jpeg' }))
  await user.upload(screen.getByLabelText('Photos or videos'), files)
  expect(await screen.findByRole('alert')).toHaveTextContent('Choose up to 5 photos or videos.')
  expect(screen.queryByRole('img', { name: /preview/i })).not.toBeInTheDocument()
})
it('shows a multi-item memory as a slideshow and a single one plainly', async () => {
  mocks.fetch.mockResolvedValue([memory('set', ['lin/person/1.jpg', 'lin/person/2.jpg']), memory('one')])
  render(<LinMemories lin={lin} />)
  expect(await screen.findByRole('group', { name: 'set, 2 items' })).toBeInTheDocument()
  expect(screen.getByText('1 of 2')).toBeInTheDocument()
  expect(screen.getByRole('img', { name: 'one' })).toHaveAttribute('src', 'blob:lin/person/one.jpg')
  expect(screen.queryByRole('group', { name: /one/ })).not.toBeInTheDocument()
})
